### ISSUE TITLE
Proper error handling 

### ISSUE THREAD

**Issue by DefCon-007** [kossiitkgp/bhattu#3]
Errors are not handled properly in bhattu. Flash can be used to report errors in real time.

**Comment by DefCon-007** [comment]
@americast : You can use https://github.com/kossiitkgp/kwoc/blob/master/app.py#L433-L445 to send error messages to #flashpoint

**Comment by americast** [comment]
@DefCon-007 Resolved in PR #7

**Comment by DefCon-007** [comment]
@americast Next remember to add " Fixes #<issue no> " in commit message. :)
